// Kits
export const LANDING_GOODS_REQUEST = 'LANDING_GOODS_REQUEST';
export const LANDING_GOODS_SUCCESS = 'LANDING_GOODS_SUCCESS';
export const LANDING_GOODS_FAILURE = 'LANDING_GOODS_FAILURE';

// Kits
export const GOODS_BANNER_REQUEST = 'GOODS_BANNER_REQUEST';
export const GOODS_BANNER_SUCCESS = 'GOODS_BANNER_SUCCESS';
export const GOODS_BANNER_FAILURE = 'GOODS_BANNER_FAILURE';

// Main Banner
export const MAIN_BANNER_REQUEST = 'MAIN_BANNER_REQUEST';
export const MAIN_BANNER_SUCCESS = 'MAIN_BANNER_SUCCESS';
export const MAIN_BANNER_FAILURE = 'MAIN_BANNER_FAILURE';
