// Kits
export const GOODS_KIT_REQUEST = 'GOODS_KIT_REQUEST';
export const GOODS_KIT_SUCCESS = 'GOODS_KIT_SUCCESS';
export const GOODS_KIT_FAILURE = 'GOODS_KIT_FAILURE';
export const LOAD_MORE_GOODS_KIT_REQUEST = 'LOAD_MORE_GOODS_KIT_REQUEST';
export const LOAD_MORE_GOODS_KIT_SUCCESS = 'LOAD_MORE_GOODS_KIT_SUCCESS';
export const LOAD_MORE_GOODS_KIT_FAILURE = 'LOAD_MORE_GOODS_KIT_FAILURE';

// Banners
export const KITS_BANNERS_REQUEST = 'KITS_BANNERS_REQUEST';
export const KITS_BANNERS_SUCCESS = 'KITS_BANNERS_SUCCESS';
export const KITS_BANNERS_FAILURE = 'KITS_BANNERS_FAILURE';

// Main Banner
export const LANDING_PAGE_REQUEST = 'LANDING_PAGE_REQUEST';
export const LANDING_PAGE_SUCCESS = 'LANDING_PAGE_SUCCESS';
export const LANDING_PAGE_FAILURE = 'LANDING_PAGE_FAILURE';

// Navigation Elements
export const NAVIGATION_ELEMENTS_REQUEST = 'NAVIGATION_ELEMENTS_REQUEST';
export const NAVIGATION_ELEMENTS_SUCCESS = 'NAVIGATION_ELEMENTS_SUCCESS';
export const NAVIGATION_ELEMENTS_FAILURE = 'NAVIGATION_ELEMENTS_FAILURE';
